insert logs

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,9 +29,13 @@ jobs:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            cd D:\BackendAssignment\HelloApi || exit 1
-            git pull origin main || exit 1
-            pm2 restart index.js || exit 1
+            echo "Running script..."
+            cd D:\BackendAssignment\HelloApi || (echo "Failed to change directory" && exit 1)
+            echo "Changed directory successfully"
+            git pull origin main || (echo "Failed to pull from Git repository" && exit 1)
+            echo "Git pull successful"
+            pm2 restart index.js || (echo "Failed to restart application with pm2" && exit 1)
+            echo "Application restarted successfully"
 
       - name: Test Deployment
         run: |
